#include <iostream>

class emptyClass {
};	// The compiler assigns the class some nonsense data that takes space
	// The adress operator (&) is also generated by the compiler
	// default ctor ("emptyClass()") is generated by the compiler
	// copy ctor is also generated by compiler
	// destructor is also generated by compiler
	// assignment is generated by compiler
	
int main()
{
	emptyClass obj1; // ok (default ctor
	emptyClass obj2(obj1); // also ok (copy ctor)
	// copy ctor calls copy ctor of the member variables
	obj1 = obj2; // assignment
	emptyClass* p = &obj1; // ok, obj1 has adress (since it contains nonsense data)
	//obj1 == obj2; // compile error, not defined
	//obj1 + obj2; // compile error, not defined
	emptyClass obj3 = obj2; // same as copy ctor (use that syntax instead)
	// plus a destructor, calling members and base class' destructors
}
